spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot2
    username: root
    password: password
    platform: mysql
    #  Seems like database initialization (running data.sql script) only works for embedded databases (H2, HSQLDB, ...).
    # If we want to use it for other databases as well, we need to set: `initialization-mode: always`
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true